In [7]:
#LOAD LIBRARIES 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
#LOAD DATASET
leuanalysisNew1data = pd.read_csv('./leuanalysisNew1.csv')
leuanalysisNew1data.head()

   CELL  SMEAR  INFIL   LI  BLAST  TEMP  REMISS
0   0.8   0.83   0.66  1.9   1.10  1.00       1
1   0.9   0.36   0.32  1.4   0.74  0.99       1
2   0.8   0.88   0.70  0.8   0.18  0.98       0
3   1.0   0.87   0.87  0.7   1.05  0.99       0
4   0.9   0.75   0.68  1.3   0.52  0.98       1

In [9]:
#SHOW KEY STATISTICS
leuanalysisNew1data.describe()

,CELL,SMEAR,INFIL,LI,BLAST,TEMP,REMISS
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,0.881481,0.635185,0.570741,1.003704,0.688519,0.997407,0.333333
std,0.186645,0.214052,0.237567,0.467795,0.534960,0.014830,0.480384
min,0.200000,0.320000,0.080000,0.400000,0.000000,0.980000,0.000000
25%,0.825000,0.430000,0.335000,0.650000,0.230000,0.990000,0.000000
50%,0.950000,0.650000,0.630000,0.900000,0.520000,0.990000,0.000000
75%,1.000000,0.835000,0.740000,1.250000,1.060000,1.005000,1.000000
max,1.000000,0.970000,0.920000,1.900000,2.060000,1.040000,1.000000

In [10]:
#Create x and y variables
x = leuanalysisNew1data.drop('REMISS',axis = 1).to_numpy()
y = leuanalysisNew1data['REMISS'].to_numpy()

#Create Training and Test Datasets
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y, stratify=y,test_size=0.2,random_state=100)

#Scale the Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [11]:
#Script for SVM and NB
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix


for name,method in [('SVM', SVC(kernel='linear',random_state=100)),
                    ('Naive Bayes',GaussianNB())]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    print('\nEstimator: {}'.format(name))  
    print(confusion_matrix(y_test,predict))
    print(classification_report(y_test,predict,zero_division=0))

Estimator: SVM
[[2 2]
 [1 1]]
              precision    recall  f1-score   support

           0       0.67      0.50      0.57         4
           1       0.33      0.50      0.40         2

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.56      0.50      0.51         6


Estimator: Naive Bayes
[[4 0]
 [2 0]]
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         4
           1       0.00      0.00      0.00         2

    accuracy                           0.67         6
   macro avg       0.33      0.50      0.40         6
weighted avg       0.44      0.67      0.53         6